
package uy.com.bse.persistence.proxy.polizasservicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWsServiciosPolizas", targetNamespace = "http://ws.polizas.bse.com.uy/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWsServiciosPolizas {


    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerDeclaracionSiniestro
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDeclaracionSiniestro", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDeclaracionSiniestro")
    @ResponseWrapper(localName = "obtenerDeclaracionSiniestroResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDeclaracionSiniestroResponse")
    public ResultObtenerDeclaracionSiniestro obtenerDeclaracionSiniestro(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerDeclaracionSiniestro arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerAseguradoCertifPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerAseguradoCertifPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerAseguradoCertifPoliza")
    @ResponseWrapper(localName = "obtenerAseguradoCertifPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerAseguradoCertifPolizaResponse")
    public ResultObtenerAseguradoCertifPoliza obtenerAseguradoCertifPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerAseguradoCertifPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultActualizarDatosParticulares
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarDatosParticulares", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ActualizarDatosParticulares")
    @ResponseWrapper(localName = "actualizarDatosParticularesResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ActualizarDatosParticularesResponse")
    public ResultActualizarDatosParticulares actualizarDatosParticulares(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamActualizarDatosParticulares arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerRemesasPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerRemesasPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerRemesasPoliza")
    @ResponseWrapper(localName = "obtenerRemesasPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerRemesasPolizaResponse")
    public ResultObtenerRemesasPoliza obtenerRemesasPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerRemesasPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultValidarPolizaRec
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarPolizaRecuotificacion", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ValidarPolizaRecuotificacion")
    @ResponseWrapper(localName = "validarPolizaRecuotificacionResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ValidarPolizaRecuotificacionResponse")
    public ResultValidarPolizaRec validarPolizaRecuotificacion(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamValidarPolizaRec arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultDatosXDatosParametricosEndoso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDatosXDatoParametricoEndoso", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosXDatoParametricoEndoso")
    @ResponseWrapper(localName = "obtenerDatosXDatoParametricoEndosoResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosXDatoParametricoEndosoResponse")
    public ResultDatosXDatosParametricosEndoso obtenerDatosXDatoParametricoEndoso(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamDatosXDatosParametricosEndoso arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultCondicion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tienePermisoProducto", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.TienePermisoProducto")
    @ResponseWrapper(localName = "tienePermisoProductoResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.TienePermisoProductoResponse")
    public ResultCondicion tienePermisoProducto(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamTienePermisoProducto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultListaPlanesPagoRec
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaPlanesPagoRecuotificacion", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaPlanesPagoRecuotificacion")
    @ResponseWrapper(localName = "listaPlanesPagoRecuotificacionResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaPlanesPagoRecuotificacionResponse")
    public ResultListaPlanesPagoRec listaPlanesPagoRecuotificacion(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamListaPlanesPagoRec arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerBonifNoSiniestroPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerBonifNoSiniestroPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerBonifNoSiniestroPoliza")
    @ResponseWrapper(localName = "obtenerBonifNoSiniestroPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerBonifNoSiniestroPolizaResponse")
    public ResultObtenerBonifNoSiniestroPoliza obtenerBonifNoSiniestroPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerBonifNoSiniestroPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerAnexosPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerAnexosPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerAnexosPoliza")
    @ResponseWrapper(localName = "obtenerAnexosPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerAnexosPolizaResponse")
    public ResultObtenerAnexosPoliza obtenerAnexosPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerAnexosPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultCodiguera
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerValoresXDatoParametrico", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerValoresXDatoParametrico")
    @ResponseWrapper(localName = "obtenerValoresXDatoParametricoResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerValoresXDatoParametricoResponse")
    public ResultCodiguera obtenerValoresXDatoParametrico(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerValoresXDatoParametrico arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultTipoCarta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaTiposCarta", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaTiposCarta")
    @ResponseWrapper(localName = "listaTiposCartaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaTiposCartaResponse")
    public ResultTipoCarta listaTiposCarta(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamTipoCarta arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerCuotasPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerCuotasPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerCuotasPoliza")
    @ResponseWrapper(localName = "obtenerCuotasPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerCuotasPolizaResponse")
    public ResultObtenerCuotasPoliza obtenerCuotasPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerCuotasPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerAcreedoresPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerAcreedoresPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerAcreedoresPoliza")
    @ResponseWrapper(localName = "obtenerAcreedoresPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerAcreedoresPolizaResponse")
    public ResultObtenerAcreedoresPoliza obtenerAcreedoresPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerAcreedoresPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultValoresDatosParametricosEndoso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaValoresDatosParametricosEndoso", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaValoresDatosParametricosEndoso")
    @ResponseWrapper(localName = "listaValoresDatosParametricosEndosoResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaValoresDatosParametricosEndosoResponse")
    public ResultValoresDatosParametricosEndoso listaValoresDatosParametricosEndoso(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamValoresDatosParametricosEndoso arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerDetalleTextoPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDetalleTextoPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDetalleTextoPoliza")
    @ResponseWrapper(localName = "obtenerDetalleTextoPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDetalleTextoPolizaResponse")
    public ResultObtenerDetalleTextoPoliza obtenerDetalleTextoPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerDetalleTextoPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerBeneficiariosPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerBeneficiariosPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerBeneficiariosPoliza")
    @ResponseWrapper(localName = "obtenerBeneficiariosPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerBeneficiariosPolizaResponse")
    public ResultObtenerBeneficiariosPoliza obtenerBeneficiariosPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerBeneficiariosPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultGenerarEndoso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarEndoso", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.GenerarEndoso")
    @ResponseWrapper(localName = "generarEndosoResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.GenerarEndosoResponse")
    public ResultGenerarEndoso generarEndoso(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamGenerarEndoso arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultRecuotificarPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuotificarPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.RecuotificarPoliza")
    @ResponseWrapper(localName = "recuotificarPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.RecuotificarPolizaResponse")
    public ResultRecuotificarPoliza recuotificarPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamRecuotificarPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultCartaXTipoCarta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaCartaXTipoCarta", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaCartaXTipoCarta")
    @ResponseWrapper(localName = "listaCartaXTipoCartaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaCartaXTipoCartaResponse")
    public ResultCartaXTipoCarta listaCartaXTipoCarta(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamCartaXTipoCarta arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultMotivoAbandono
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaMotivoAbandono", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaMotivoAbandono")
    @ResponseWrapper(localName = "listaMotivoAbandonoResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaMotivoAbandonoResponse")
    public ResultMotivoAbandono listaMotivoAbandono(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamMotivoAbandono arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerDetallePoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDetallePoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDetallePoliza")
    @ResponseWrapper(localName = "obtenerDetallePolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDetallePolizaResponse")
    public ResultObtenerDetallePoliza obtenerDetallePoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerDetallePoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultNuevaFacturacionInteractiva
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nuevaFacturacionInteractiva", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.NuevaFacturacionInteractiva")
    @ResponseWrapper(localName = "nuevaFacturacionInteractivaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.NuevaFacturacionInteractivaResponse")
    public ResultNuevaFacturacionInteractiva nuevaFacturacionInteractiva(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamNuevaFacturacionInteractiva arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerNotasSiniestro
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerNotasSiniestro", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerNotasSiniestro")
    @ResponseWrapper(localName = "obtenerNotasSiniestroResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerNotasSiniestroResponse")
    public ResultObtenerNotasSiniestro obtenerNotasSiniestro(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerNotasSiniestro arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerDatosCertificadoPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDatosCertificadoPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosCertificadoPoliza")
    @ResponseWrapper(localName = "obtenerDatosCertificadoPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosCertificadoPolizaResponse")
    public ResultObtenerDatosCertificadoPoliza obtenerDatosCertificadoPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerDatosCertificadoPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerPolizas
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerPolizas", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerPolizas")
    @ResponseWrapper(localName = "obtenerPolizasResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerPolizasResponse")
    public ResultObtenerPolizas obtenerPolizas(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerPolizas arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerBienesAseguradosPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerBienesAseguradosPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerBienesAseguradosPoliza")
    @ResponseWrapper(localName = "obtenerBienesAseguradosPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerBienesAseguradosPolizaResponse")
    public ResultObtenerBienesAseguradosPoliza obtenerBienesAseguradosPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerBienesAseguradosPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerConsolidado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerConsolidadoPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerConsolidadoPoliza")
    @ResponseWrapper(localName = "obtenerConsolidadoPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerConsolidadoPolizaResponse")
    public ResultObtenerConsolidado obtenerConsolidadoPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerConsolidado arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultAnularCertificadoEndoso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "anularCertificadoEndoso", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.AnularCertificadoEndoso")
    @ResponseWrapper(localName = "anularCertificadoEndosoResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.AnularCertificadoEndosoResponse")
    public ResultAnularCertificadoEndoso anularCertificadoEndoso(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamAnularCertificadoEndoso arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerFacturasPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerFacturasPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerFacturasPoliza")
    @ResponseWrapper(localName = "obtenerFacturasPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerFacturasPolizaResponse")
    public ResultObtenerFacturasPoliza obtenerFacturasPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerFacturasPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultAcreedorObjetos
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaAcreedorObjetos", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaAcreedorObjetos")
    @ResponseWrapper(localName = "listaAcreedorObjetosResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaAcreedorObjetosResponse")
    public ResultAcreedorObjetos listaAcreedorObjetos(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObjetosAcreedor arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultModificacionSinPremio
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificacionSinPremio", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ModificacionSinPremio")
    @ResponseWrapper(localName = "modificacionSinPremioResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ModificacionSinPremioResponse")
    public ResultModificacionSinPremio modificacionSinPremio(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamModificacionSinPremio arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerProductoresPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerProductoresPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerProductoresPoliza")
    @ResponseWrapper(localName = "obtenerProductoresPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerProductoresPolizaResponse")
    public ResultObtenerProductoresPoliza obtenerProductoresPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerProductoresPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerDatosEndosoPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDatosEndosoPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosEndosoPoliza")
    @ResponseWrapper(localName = "obtenerDatosEndosoPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosEndosoPolizaResponse")
    public ResultObtenerDatosEndosoPoliza obtenerDatosEndosoPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerDatosEndosoPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultMotivoEndoso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaMotivosEndoso", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaMotivosEndoso")
    @ResponseWrapper(localName = "listaMotivosEndosoResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaMotivosEndosoResponse")
    public ResultMotivoEndoso listaMotivosEndoso(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamMotivoEndoso arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerPolizaCabezalDetalle
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerPolizaCabezalDetalle", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerPolizaCabezalDetalle")
    @ResponseWrapper(localName = "obtenerPolizaCabezalDetalleResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerPolizaCabezalDetalleResponse")
    public ResultObtenerPolizaCabezalDetalle obtenerPolizaCabezalDetalle(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerPolizaCabezalDetalle arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultTipoAnulacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaTipoAnulacion", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaTipoAnulacion")
    @ResponseWrapper(localName = "listaTipoAnulacionResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaTipoAnulacionResponse")
    public ResultTipoAnulacion listaTipoAnulacion(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamTipoAnulacion arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerTotalesCuotasPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerTotalesCuotasPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerTotalesCuotasPoliza")
    @ResponseWrapper(localName = "obtenerTotalesCuotasPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerTotalesCuotasPolizaResponse")
    public ResultObtenerTotalesCuotasPoliza obtenerTotalesCuotasPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerTotalesCuotasPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerSiniestrosCliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerSiniestrosCliente", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerSiniestrosCliente")
    @ResponseWrapper(localName = "obtenerSiniestrosClienteResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerSiniestrosClienteResponse")
    public ResultObtenerSiniestrosCliente obtenerSiniestrosCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerSiniestrosCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerDatosSiniestro
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDatosSiniestro", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosSiniestro")
    @ResponseWrapper(localName = "obtenerDatosSiniestroResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosSiniestroResponse")
    public ResultObtenerDatosSiniestro obtenerDatosSiniestro(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerDatosSiniestro arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultDatosXDatosParametricosPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDatosXDatoParametricoPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosXDatoParametricoPoliza")
    @ResponseWrapper(localName = "obtenerDatosXDatoParametricoPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosXDatoParametricoPolizaResponse")
    public ResultDatosXDatosParametricosPoliza obtenerDatosXDatoParametricoPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamDatosXDatosParametricosPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerCancelacionesRemesa
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerCancelacionesRemesa", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerCancelacionesRemesa")
    @ResponseWrapper(localName = "obtenerCancelacionesRemesaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerCancelacionesRemesaResponse")
    public ResultObtenerCancelacionesRemesa obtenerCancelacionesRemesa(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerCancelacionesRemesa arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultCalcularRec
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcularRecuotificacion", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.CalcularRecuotificacion")
    @ResponseWrapper(localName = "calcularRecuotificacionResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.CalcularRecuotificacionResponse")
    public ResultCalcularRec calcularRecuotificacion(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamCalcularRec arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerDatosEndosoSinPremio
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDatosEndosoSinPremio", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosEndosoSinPremio")
    @ResponseWrapper(localName = "obtenerDatosEndosoSinPremioResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosEndosoSinPremioResponse")
    public ResultObtenerDatosEndosoSinPremio obtenerDatosEndosoSinPremio(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerDatosEndosoSinPremio arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerDebitosAutomaticosPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDebitosAutomaticosPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDebitosAutomaticosPoliza")
    @ResponseWrapper(localName = "obtenerDebitosAutomaticosPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDebitosAutomaticosPolizaResponse")
    public ResultObtenerDebitosAutomaticosPoliza obtenerDebitosAutomaticosPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerDebitosAutomaticosPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerPolizasCabezal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerPolizasCabezal", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerPolizasCabezal")
    @ResponseWrapper(localName = "obtenerPolizasCabezalResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerPolizasCabezalResponse")
    public ResultObtenerPolizasCabezal obtenerPolizasCabezal(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerPolizasCabezal arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultEndosoSPDocumentacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "endosoSPDocumentacion", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.EndosoSPDocumentacion")
    @ResponseWrapper(localName = "endosoSPDocumentacionResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.EndosoSPDocumentacionResponse")
    public ResultEndosoSPDocumentacion endosoSPDocumentacion(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamEndosoSPDocumentacion arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerDatosBasicosEndoso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDatosBasicosEndoso", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosBasicosEndoso")
    @ResponseWrapper(localName = "obtenerDatosBasicosEndosoResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosBasicosEndosoResponse")
    public ResultObtenerDatosBasicosEndoso obtenerDatosBasicosEndoso(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerDatosBasicosEndoso arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerDatosFacturaDigital
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDatosFacturaDigital", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosFacturaDigital")
    @ResponseWrapper(localName = "obtenerDatosFacturaDigitalResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosFacturaDigitalResponse")
    public ResultObtenerDatosFacturaDigital obtenerDatosFacturaDigital(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerDatosFacturaDigital arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerDetalleRemesa
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDetalleRemesa", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDetalleRemesa")
    @ResponseWrapper(localName = "obtenerDetalleRemesaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDetalleRemesaResponse")
    public ResultObtenerDetalleRemesa obtenerDetalleRemesa(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerDetalleRemesa arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerAsesorPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerAsesorPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerAsesorPoliza")
    @ResponseWrapper(localName = "obtenerAsesorPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerAsesorPolizaResponse")
    public ResultObtenerAsesorPoliza obtenerAsesorPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerAsesorPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerAhorrosPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerAhorrosPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerAhorrosPoliza")
    @ResponseWrapper(localName = "obtenerAhorrosPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerAhorrosPolizaResponse")
    public ResultObtenerAhorrosPoliza obtenerAhorrosPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerAhorrosPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultAnularPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "anularPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.AnularPoliza")
    @ResponseWrapper(localName = "anularPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.AnularPolizaResponse")
    public ResultAnularPoliza anularPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamAnularPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultValidarAnulacionPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarAnulacionPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ValidarAnulacionPoliza")
    @ResponseWrapper(localName = "validarAnulacionPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ValidarAnulacionPolizaResponse")
    public ResultValidarAnulacionPoliza validarAnulacionPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamValidarAnulacionPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultValoresDatosParametricosPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaValoresDatosParametricosPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaValoresDatosParametricosPoliza")
    @ResponseWrapper(localName = "listaValoresDatosParametricosPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaValoresDatosParametricosPolizaResponse")
    public ResultValoresDatosParametricosPoliza listaValoresDatosParametricosPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamValoresDatosParametricosPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultEndosoSPFactura
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "endosoSPFactura", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.EndosoSPFactura")
    @ResponseWrapper(localName = "endosoSPFacturaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.EndosoSPFacturaResponse")
    public ResultEndosoSPFactura endosoSPFactura(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamEndosoSPFactura arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultGuardarImprimirReporte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "guardarImprimirReporte", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.GuardarImprimirReporte")
    @ResponseWrapper(localName = "guardarImprimirReporteResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.GuardarImprimirReporteResponse")
    public ResultGuardarImprimirReporte guardarImprimirReporte(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamGuardarImprimirReporte arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerSiniestrosConFiltro
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerSiniestrosConFiltro", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerSiniestrosConFiltro")
    @ResponseWrapper(localName = "obtenerSiniestrosConFiltroResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerSiniestrosConFiltroResponse")
    public ResultObtenerSiniestrosConFiltro obtenerSiniestrosConFiltro(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerSiniestrosConFiltro arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerPreliqPendientesPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerPreliqPendientesPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerPreliqPendientesPoliza")
    @ResponseWrapper(localName = "obtenerPreliqPendientesPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerPreliqPendientesPolizaResponse")
    public ResultObtenerPreliqPendientesPoliza obtenerPreliqPendientesPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerPreliqPendientesPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultModoCalculo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaModoCalculoAnulacion", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaModoCalculoAnulacion")
    @ResponseWrapper(localName = "listaModoCalculoAnulacionResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaModoCalculoAnulacionResponse")
    public ResultModoCalculo listaModoCalculoAnulacion(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamModoCalculo arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerValidarImpresionPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerValidarImpresionPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerValidarImpresionPoliza")
    @ResponseWrapper(localName = "obtenerValidarImpresionPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerValidarImpresionPolizaResponse")
    public ResultObtenerValidarImpresionPoliza obtenerValidarImpresionPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerValidarImpresionPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultValidarPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ValidarPoliza")
    @ResponseWrapper(localName = "validarPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ValidarPolizaResponse")
    public ResultValidarPoliza validarPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamValidarPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerRemesasXCliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerRemesasXCliente", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerRemesasXCliente")
    @ResponseWrapper(localName = "obtenerRemesasXClienteResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerRemesasXClienteResponse")
    public ResultObtenerRemesasXCliente obtenerRemesasXCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerRemesasXCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerDatosRemesa
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDatosRemesa", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosRemesa")
    @ResponseWrapper(localName = "obtenerDatosRemesaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosRemesaResponse")
    public ResultObtenerDatosRemesa obtenerDatosRemesa(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerDatosRemesa arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerSiniestros
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerSiniestros", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerSiniestros")
    @ResponseWrapper(localName = "obtenerSiniestrosResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerSiniestrosResponse")
    public ResultObtenerSiniestros obtenerSiniestros(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerSiniestros arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerUbicacionBienPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerUbicacionBienPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerUbicacionBienPoliza")
    @ResponseWrapper(localName = "obtenerUbicacionBienPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerUbicacionBienPolizaResponse")
    public ResultObtenerUbicacionBienPoliza obtenerUbicacionBienPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerUbicacionBienPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerTextosPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerTextosPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerTextosPoliza")
    @ResponseWrapper(localName = "obtenerTextosPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerTextosPolizaResponse")
    public ResultObtenerTextosPoliza obtenerTextosPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerTextosPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultGenerarMarcaNoRenovar
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarMarcaNoRenovar", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.GenerarMarcaNoRenovar")
    @ResponseWrapper(localName = "generarMarcaNoRenovarResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.GenerarMarcaNoRenovarResponse")
    public ResultGenerarMarcaNoRenovar generarMarcaNoRenovar(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamGenerarMarcaNoRenovar arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultCausaAnulacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaCausaAnulacion", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaCausaAnulacion")
    @ResponseWrapper(localName = "listaCausaAnulacionResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaCausaAnulacionResponse")
    public ResultCausaAnulacion listaCausaAnulacion(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamCausaAnulacion arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultOrigenEndoso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaOrigenEndoso", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaOrigenEndoso")
    @ResponseWrapper(localName = "listaOrigenEndosoResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaOrigenEndosoResponse")
    public ResultOrigenEndoso listaOrigenEndoso(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamOrigenEndoso arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultGuardarImprimirOrdenCarta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "guardarImprimirOrdenCarta", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.GuardarImprimirOrdenCarta")
    @ResponseWrapper(localName = "guardarImprimirOrdenCartaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.GuardarImprimirOrdenCartaResponse")
    public ResultGuardarImprimirOrdenCarta guardarImprimirOrdenCarta(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamGuardarImprimirCarta arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerFranquiciasPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerFranquiciasPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerFranquiciasPoliza")
    @ResponseWrapper(localName = "obtenerFranquiciasPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerFranquiciasPolizaResponse")
    public ResultObtenerFranquiciasPoliza obtenerFranquiciasPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerFranquiciasPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerContratantePoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerContratantePoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerContratantePoliza")
    @ResponseWrapper(localName = "obtenerContratantePolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerContratantePolizaResponse")
    public ResultObtenerContratantePoliza obtenerContratantePoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerContratantePoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerOrigenRemesaAuto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerOrigenRemesaAutomatica", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerOrigenRemesaAutomatica")
    @ResponseWrapper(localName = "obtenerOrigenRemesaAutomaticaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerOrigenRemesaAutomaticaResponse")
    public ResultObtenerOrigenRemesaAuto obtenerOrigenRemesaAutomatica(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerOrigenRemesaAuto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultCotizacionPendiente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cotizacionPendientePoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.CotizacionPendientePoliza")
    @ResponseWrapper(localName = "cotizacionPendientePolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.CotizacionPendientePolizaResponse")
    public ResultCotizacionPendiente cotizacionPendientePoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamCotizacionPendiente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultCotizacionPendiente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cotizacionPendientePolizaSinPremio", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.CotizacionPendientePolizaSinPremio")
    @ResponseWrapper(localName = "cotizacionPendientePolizaSinPremioResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.CotizacionPendientePolizaSinPremioResponse")
    public ResultCotizacionPendiente cotizacionPendientePolizaSinPremio(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamCotizacionPendienteSinPremio arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerCotizacionPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerCotizacionPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerCotizacionPoliza")
    @ResponseWrapper(localName = "obtenerCotizacionPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerCotizacionPolizaResponse")
    public ResultObtenerCotizacionPoliza obtenerCotizacionPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerCotizacionPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerImputacionesPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerImputacionesPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerImputacionesPoliza")
    @ResponseWrapper(localName = "obtenerImputacionesPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerImputacionesPolizaResponse")
    public ResultObtenerImputacionesPoliza obtenerImputacionesPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerImputacionesPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultAgregarCertificadoEndoso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "agregarCertificadoEndoso", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.AgregarCertificadoEndoso")
    @ResponseWrapper(localName = "agregarCertificadoEndosoResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.AgregarCertificadoEndosoResponse")
    public ResultAgregarCertificadoEndoso agregarCertificadoEndoso(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamAgregarCertificadoEndoso arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultValidarRefacturacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarRefacturacion", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ValidarRefacturacion")
    @ResponseWrapper(localName = "validarRefacturacionResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ValidarRefacturacionResponse")
    public ResultValidarRefacturacion validarRefacturacion(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamValidarRefacturacion arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultDatosParametricosEndoso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaDatosParametricosEndoso", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaDatosParametricosEndoso")
    @ResponseWrapper(localName = "listaDatosParametricosEndosoResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaDatosParametricosEndosoResponse")
    public ResultDatosParametricosEndoso listaDatosParametricosEndoso(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamDatosParametricosEndoso arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerEndososPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerEndososPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerEndososPoliza")
    @ResponseWrapper(localName = "obtenerEndososPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerEndososPolizaResponse")
    public ResultObtenerEndososPoliza obtenerEndososPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerEndososPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerListaBienesPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerListaBienesPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerListaBienesPoliza")
    @ResponseWrapper(localName = "obtenerListaBienesPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerListaBienesPolizaResponse")
    public ResultObtenerListaBienesPoliza obtenerListaBienesPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerListaBienesPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultDatosParametricoPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaDatosParametricosPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaDatosParametricosPoliza")
    @ResponseWrapper(localName = "listaDatosParametricosPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaDatosParametricosPolizaResponse")
    public ResultDatosParametricoPoliza listaDatosParametricosPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamDatosParametricoPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultCodiguera
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaCertificadosParaEndosar", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaCertificadosParaEndosar")
    @ResponseWrapper(localName = "listaCertificadosParaEndosarResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ListaCertificadosParaEndosarResponse")
    public ResultCodiguera listaCertificadosParaEndosar(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamListaCertificadosEndosar arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerCertificadosPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerCertificadosPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerCertificadosPoliza")
    @ResponseWrapper(localName = "obtenerCertificadosPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerCertificadosPolizaResponse")
    public ResultObtenerCertificadosPoliza obtenerCertificadosPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerCertificadosPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultEnviarFacturaDigitalEMail
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enviarFacturaDigitalEMail", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.EnviarFacturaDigitalEMail")
    @ResponseWrapper(localName = "enviarFacturaDigitalEMailResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.EnviarFacturaDigitalEMailResponse")
    public ResultEnviarFacturaDigitalEMail enviarFacturaDigitalEMail(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamEnviarFacturaDigitalEMail arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerDatosPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDatosPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosPoliza")
    @ResponseWrapper(localName = "obtenerDatosPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosPolizaResponse")
    public ResultObtenerDatosPoliza obtenerDatosPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerDatosPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultObtenerDatosParametricos
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDatosParametricos", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosParametricos")
    @ResponseWrapper(localName = "obtenerDatosParametricosResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ObtenerDatosParametricosResponse")
    public ResultObtenerDatosParametricos obtenerDatosParametricos(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerDatosParametricos arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultValidarDetectarEndoso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarDetectarEndoso", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ValidarDetectarEndoso")
    @ResponseWrapper(localName = "validarDetectarEndosoResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.ValidarDetectarEndosoResponse")
    public ResultValidarDetectarEndoso validarDetectarEndoso(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamValidarDetectarEndoso arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultNuevaCotizacionEndoso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nuevaCotizacionEndoso", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.NuevaCotizacionEndoso")
    @ResponseWrapper(localName = "nuevaCotizacionEndosoResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.NuevaCotizacionEndosoResponse")
    public ResultNuevaCotizacionEndoso nuevaCotizacionEndoso(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamNuevaCotizacionEndoso arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.polizasservicios.ResultRefacturacionPoliza
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "refacturarPoliza", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.RefacturarPoliza")
    @ResponseWrapper(localName = "refacturarPolizaResponse", targetNamespace = "http://ws.polizas.bse.com.uy/", className = "uy.com.bse.persistence.proxy.polizasservicios.RefacturarPolizaResponse")
    public ResultRefacturacionPoliza refacturarPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamRefacturarPoliza arg0);

}
