
package uy.com.bse.persistence.proxy.mibse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWsServiciosMiBse", targetNamespace = "http://ws.mibse.bse.com.uy/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWsServiciosMiBse {


    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultObtenerMailCliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerSeudoMailCliente", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerSeudoMailCliente")
    @ResponseWrapper(localName = "obtenerSeudoMailClienteResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerSeudoMailClienteResponse")
    public ResultObtenerMailCliente obtenerSeudoMailCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerMailCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultSubirArchivo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subirArchivo", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.SubirArchivo")
    @ResponseWrapper(localName = "subirArchivoResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.SubirArchivoResponse")
    public ResultSubirArchivo subirArchivo(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamSubirArchivo arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultProCarta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "proCarta", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ProCarta")
    @ResponseWrapper(localName = "proCartaResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ProCartaResponse")
    public ResultProCarta proCarta(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamProCarta arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultObtenerDatosValidadosCliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDatosValidadosCliente", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerDatosValidadosCliente")
    @ResponseWrapper(localName = "obtenerDatosValidadosClienteResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerDatosValidadosClienteResponse")
    public ResultObtenerDatosValidadosCliente obtenerDatosValidadosCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerDatosValidadosCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultLogActividadMibseWsExt
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logActividadMibseWsExt", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.LogActividadMibseWsExt")
    @ResponseWrapper(localName = "logActividadMibseWsExtResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.LogActividadMibseWsExtResponse")
    public ResultLogActividadMibseWsExt logActividadMibseWsExt(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamLogActividadMibseWsExt arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultGenerico
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "altaMailCliente", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.AltaMailCliente")
    @ResponseWrapper(localName = "altaMailClienteResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.AltaMailClienteResponse")
    public ResultGenerico altaMailCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamAltaMailCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultObtenerPolizasCliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerPolizasCliente", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerPolizasCliente")
    @ResponseWrapper(localName = "obtenerPolizasClienteResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerPolizasClienteResponse")
    public ResultObtenerPolizasCliente obtenerPolizasCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerPolizasCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultObtenerPolizasFacturasPagasCliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerPolizasFacturasPagasCliente", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerPolizasFacturasPagasCliente")
    @ResponseWrapper(localName = "obtenerPolizasFacturasPagasClienteResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerPolizasFacturasPagasClienteResponse")
    public ResultObtenerPolizasFacturasPagasCliente obtenerPolizasFacturasPagasCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerPolizasFacturasPagasCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultValidacionSOA
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validacionSOA", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ValidacionSOA")
    @ResponseWrapper(localName = "validacionSOAResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ValidacionSOAResponse")
    public ResultValidacionSOA validacionSOA(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamValidacionSOA arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultInformarPagoBancario
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "informarPagoBancario", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.InformarPagoBancario")
    @ResponseWrapper(localName = "informarPagoBancarioResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.InformarPagoBancarioResponse")
    public ResultInformarPagoBancario informarPagoBancario(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamInformarPagoBancario arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultAdherirFacturaDigital
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "adherirFacturaDigital", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.AdherirFacturaDigital")
    @ResponseWrapper(localName = "adherirFacturaDigitalResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.AdherirFacturaDigitalResponse")
    public ResultAdherirFacturaDigital adherirFacturaDigital(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamAdherirFacturaDigital arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultGenerico
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "borrarMailCliente", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.BorrarMailCliente")
    @ResponseWrapper(localName = "borrarMailClienteResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.BorrarMailClienteResponse")
    public ResultGenerico borrarMailCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamBorrarMailCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultInformarPagoRedes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "informarPagoRedes", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.InformarPagoRedes")
    @ResponseWrapper(localName = "informarPagoRedesResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.InformarPagoRedesResponse")
    public ResultInformarPagoRedes informarPagoRedes(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamInformarPagoRedes arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultRegistrarCliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registrarCliente", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.RegistrarCliente")
    @ResponseWrapper(localName = "registrarClienteResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.RegistrarClienteResponse")
    public ResultRegistrarCliente registrarCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamRegistrarCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultCodiguera
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaTipoDocumentos", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ListaTipoDocumentos")
    @ResponseWrapper(localName = "listaTipoDocumentosResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ListaTipoDocumentosResponse")
    public ResultCodiguera listaTipoDocumentos(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamListaTipoDocumentos arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultValidacionCartaVerde
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validacionCartaVerde", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ValidacionCartaVerde")
    @ResponseWrapper(localName = "validacionCartaVerdeResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ValidacionCartaVerdeResponse")
    public ResultValidacionCartaVerde validacionCartaVerde(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamValidacionCartaVerde arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultExisteCliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "existeCliente", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ExisteCliente")
    @ResponseWrapper(localName = "existeClienteResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ExisteClienteResponse")
    public ResultExisteCliente existeCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamExisteCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultObtenerMaximoEndoso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerMaximoEndoso", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerMaximoEndoso")
    @ResponseWrapper(localName = "obtenerMaximoEndosoResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerMaximoEndosoResponse")
    public ResultObtenerMaximoEndoso obtenerMaximoEndoso(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerMaximoEndoso arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultObtenerMailsEnvioFacturaCliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerMailsEnvioFacturaCliente", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerMailsEnvioFacturaCliente")
    @ResponseWrapper(localName = "obtenerMailsEnvioFacturaClienteResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerMailsEnvioFacturaClienteResponse")
    public ResultObtenerMailsEnvioFacturaCliente obtenerMailsEnvioFacturaCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerMailsEnvioFacturaCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultObtenerComunicacionesCliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerComunicacionesCliente", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerComunicacionesCliente")
    @ResponseWrapper(localName = "obtenerComunicacionesClienteResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerComunicacionesClienteResponse")
    public ResultObtenerComunicacionesCliente obtenerComunicacionesCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerComunicacionesCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultGenerico
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "olvidoClave", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.OlvidoClave")
    @ResponseWrapper(localName = "olvidoClaveResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.OlvidoClaveResponse")
    public ResultGenerico olvidoClave(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamOlvidoClave arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultGenerico
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarComunicacionesCliente", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ActualizarComunicacionesCliente")
    @ResponseWrapper(localName = "actualizarComunicacionesClienteResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ActualizarComunicacionesClienteResponse")
    public ResultGenerico actualizarComunicacionesCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamActualizarComunicacionesCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultValidarCodigoAdhesion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarCodigoAdhesion", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ValidarCodigoAdhesion")
    @ResponseWrapper(localName = "validarCodigoAdhesionResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ValidarCodigoAdhesionResponse")
    public ResultValidarCodigoAdhesion validarCodigoAdhesion(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamValidarCodigoAdhesion arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultValidarCertificadoLibreDeudaADT
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarCertificadoLibreDeudaADT", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ValidarCertificadoLibreDeudaADT")
    @ResponseWrapper(localName = "validarCertificadoLibreDeudaADTResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ValidarCertificadoLibreDeudaADTResponse")
    public ResultValidarCertificadoLibreDeudaADT validarCertificadoLibreDeudaADT(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamValidarCertificadoLibreDeudaADT arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultObtenerDatosCliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDatosCliente", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerDatosCliente")
    @ResponseWrapper(localName = "obtenerDatosClienteResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerDatosClienteResponse")
    public ResultObtenerDatosCliente obtenerDatosCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerDatosCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultGenerico
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarFacturacionPolizaTodo", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ActualizarFacturacionPolizaTodo")
    @ResponseWrapper(localName = "actualizarFacturacionPolizaTodoResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ActualizarFacturacionPolizaTodoResponse")
    public ResultGenerico actualizarFacturacionPolizaTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamActualizarFacturacionPolizaTodo arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultGenerico
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificarMailCliente", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ModificarMailCliente")
    @ResponseWrapper(localName = "modificarMailClienteResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ModificarMailClienteResponse")
    public ResultGenerico modificarMailCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamModificarMailCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultGenerico
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarDatosCliente", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ActualizarDatosCliente")
    @ResponseWrapper(localName = "actualizarDatosClienteResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ActualizarDatosClienteResponse")
    public ResultGenerico actualizarDatosCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamActualizarDatosCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultCodiguera
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaProfesiones", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ListaProfesiones")
    @ResponseWrapper(localName = "listaProfesionesResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ListaProfesionesResponse")
    public ResultCodiguera listaProfesiones(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamListaProfesiones arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultObtenerNumeroCliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerNumeroCliente", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerNumeroCliente")
    @ResponseWrapper(localName = "obtenerNumeroClienteResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerNumeroClienteResponse")
    public ResultObtenerNumeroCliente obtenerNumeroCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerNumeroCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultGenerico
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarFacturacionPoliza", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ActualizarFacturacionPoliza")
    @ResponseWrapper(localName = "actualizarFacturacionPolizaResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ActualizarFacturacionPolizaResponse")
    public ResultGenerico actualizarFacturacionPoliza(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamActualizarFacturacionPoliza arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.mibse.ResultObtenerMapaMsgSiniestro
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerMapaMsgSiniestro", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerMapaMsgSiniestro")
    @ResponseWrapper(localName = "obtenerMapaMsgSiniestroResponse", targetNamespace = "http://ws.mibse.bse.com.uy/", className = "uy.com.bse.persistence.proxy.mibse.ObtenerMapaMsgSiniestroResponse")
    public ResultObtenerMapaMsgSiniestro obtenerMapaMsgSiniestro(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamObtenerMapaMsgSiniestro arg0);

}
