
package uy.com.bse.persistence.proxy.mibse;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsServiciosMiBse", targetNamespace = "http://ws.mibse.bse.com.uy/", wsdlLocation = "http://jboss-test.bse.com.uy:9080/ServiciosMiBSEWS/WsServiciosMiBse?wsdl")
public class WsServiciosMiBse
    extends Service
{

    private final static URL WSSERVICIOSMIBSE_WSDL_LOCATION;
    private final static WebServiceException WSSERVICIOSMIBSE_EXCEPTION;
    private final static QName WSSERVICIOSMIBSE_QNAME = new QName("http://ws.mibse.bse.com.uy/", "WsServiciosMiBse");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://jboss-test.bse.com.uy:9080/ServiciosMiBSEWS/WsServiciosMiBse?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSERVICIOSMIBSE_WSDL_LOCATION = url;
        WSSERVICIOSMIBSE_EXCEPTION = e;
    }

    public WsServiciosMiBse() {
        super(__getWsdlLocation(), WSSERVICIOSMIBSE_QNAME);
    }

    public WsServiciosMiBse(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSERVICIOSMIBSE_QNAME, features);
    }

    public WsServiciosMiBse(URL wsdlLocation) {
        super(wsdlLocation, WSSERVICIOSMIBSE_QNAME);
    }

    public WsServiciosMiBse(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSERVICIOSMIBSE_QNAME, features);
    }

    public WsServiciosMiBse(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsServiciosMiBse(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IWsServiciosMiBse
     */
    @WebEndpoint(name = "WsServiciosMiBsePort")
    public IWsServiciosMiBse getWsServiciosMiBsePort() {
        return super.getPort(new QName("http://ws.mibse.bse.com.uy/", "WsServiciosMiBsePort"), IWsServiciosMiBse.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWsServiciosMiBse
     */
    @WebEndpoint(name = "WsServiciosMiBsePort")
    public IWsServiciosMiBse getWsServiciosMiBsePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.mibse.bse.com.uy/", "WsServiciosMiBsePort"), IWsServiciosMiBse.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSERVICIOSMIBSE_EXCEPTION!= null) {
            throw WSSERVICIOSMIBSE_EXCEPTION;
        }
        return WSSERVICIOSMIBSE_WSDL_LOCATION;
    }

}
