
package uy.com.bse.persistence.proxy.seguridadservicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWsSeguridad", targetNamespace = "http://ws.seguridad.bse.com.uy/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWsSeguridad {


    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.seguridadservicios.ResultLogout
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "http://ws.seguridad.bse.com.uy/", className = "uy.com.bse.persistence.proxy.seguridadservicios.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://ws.seguridad.bse.com.uy/", className = "uy.com.bse.persistence.proxy.seguridadservicios.LogoutResponse")
    public ResultLogout logout(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamLogout arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.seguridadservicios.ResultLogin
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://ws.seguridad.bse.com.uy/", className = "uy.com.bse.persistence.proxy.seguridadservicios.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://ws.seguridad.bse.com.uy/", className = "uy.com.bse.persistence.proxy.seguridadservicios.LoginResponse")
    public ResultLogin login(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamLogin arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.seguridadservicios.ResultLoginGroup
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loginGroup", targetNamespace = "http://ws.seguridad.bse.com.uy/", className = "uy.com.bse.persistence.proxy.seguridadservicios.LoginGroup")
    @ResponseWrapper(localName = "loginGroupResponse", targetNamespace = "http://ws.seguridad.bse.com.uy/", className = "uy.com.bse.persistence.proxy.seguridadservicios.LoginGroupResponse")
    public ResultLoginGroup loginGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamLoginGroup arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.com.bse.persistence.proxy.seguridadservicios.ResultValidar
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validar", targetNamespace = "http://ws.seguridad.bse.com.uy/", className = "uy.com.bse.persistence.proxy.seguridadservicios.Validar")
    @ResponseWrapper(localName = "validarResponse", targetNamespace = "http://ws.seguridad.bse.com.uy/", className = "uy.com.bse.persistence.proxy.seguridadservicios.ValidarResponse")
    public ResultValidar validar(
        @WebParam(name = "arg0", targetNamespace = "")
        ParamValidar arg0);

}
