
package uy.com.bse.persistence.proxy.seguridadservicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsSeguridadServicios", targetNamespace = "http://ws.seguridad.bse.com.uy/", wsdlLocation = "http://jboss-test.bse.com.uy:9080/SeguridadServiciosWS/WsSeguridadServicios?wsdl")
public class WsSeguridadServicios
    extends Service
{

    private final static URL WSSEGURIDADSERVICIOS_WSDL_LOCATION;
    private final static WebServiceException WSSEGURIDADSERVICIOS_EXCEPTION;
    private final static QName WSSEGURIDADSERVICIOS_QNAME = new QName("http://ws.seguridad.bse.com.uy/", "WsSeguridadServicios");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://jboss-test.bse.com.uy:9080/SeguridadServiciosWS/WsSeguridadServicios?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSEGURIDADSERVICIOS_WSDL_LOCATION = url;
        WSSEGURIDADSERVICIOS_EXCEPTION = e;
    }

    public WsSeguridadServicios() {
        super(__getWsdlLocation(), WSSEGURIDADSERVICIOS_QNAME);
    }

    public WsSeguridadServicios(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSEGURIDADSERVICIOS_QNAME, features);
    }

    public WsSeguridadServicios(URL wsdlLocation) {
        super(wsdlLocation, WSSEGURIDADSERVICIOS_QNAME);
    }

    public WsSeguridadServicios(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSEGURIDADSERVICIOS_QNAME, features);
    }

    public WsSeguridadServicios(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsSeguridadServicios(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IWsSeguridad
     */
    @WebEndpoint(name = "WsSeguridadServiciosPort")
    public IWsSeguridad getWsSeguridadServiciosPort() {
        return super.getPort(new QName("http://ws.seguridad.bse.com.uy/", "WsSeguridadServiciosPort"), IWsSeguridad.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWsSeguridad
     */
    @WebEndpoint(name = "WsSeguridadServiciosPort")
    public IWsSeguridad getWsSeguridadServiciosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.seguridad.bse.com.uy/", "WsSeguridadServiciosPort"), IWsSeguridad.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSEGURIDADSERVICIOS_EXCEPTION!= null) {
            throw WSSEGURIDADSERVICIOS_EXCEPTION;
        }
        return WSSEGURIDADSERVICIOS_WSDL_LOCATION;
    }

}
