
package uy.com.bse.persistence.proxy.firmaelectronica;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FirmaElectronica", targetNamespace = "http://firma.ws.servicios.bse.com/", wsdlLocation = "http://jboss-test.bse.com.uy:9080/BseFEService/FirmaElectronica?wsdl")
public class FirmaElectronica_Service
    extends Service
{

    private final static URL FIRMAELECTRONICA_WSDL_LOCATION;
    private final static WebServiceException FIRMAELECTRONICA_EXCEPTION;
    private final static QName FIRMAELECTRONICA_QNAME = new QName("http://firma.ws.servicios.bse.com/", "FirmaElectronica");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://jboss-test.bse.com.uy:9080/BseFEService/FirmaElectronica?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FIRMAELECTRONICA_WSDL_LOCATION = url;
        FIRMAELECTRONICA_EXCEPTION = e;
    }

    public FirmaElectronica_Service() {
        super(__getWsdlLocation(), FIRMAELECTRONICA_QNAME);
    }

    public FirmaElectronica_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FIRMAELECTRONICA_QNAME, features);
    }

    public FirmaElectronica_Service(URL wsdlLocation) {
        super(wsdlLocation, FIRMAELECTRONICA_QNAME);
    }

    public FirmaElectronica_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FIRMAELECTRONICA_QNAME, features);
    }

    public FirmaElectronica_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FirmaElectronica_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FirmaElectronica
     */
    @WebEndpoint(name = "FirmaElectronicaPort")
    public FirmaElectronica getFirmaElectronicaPort() {
        return super.getPort(new QName("http://firma.ws.servicios.bse.com/", "FirmaElectronicaPort"), FirmaElectronica.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FirmaElectronica
     */
    @WebEndpoint(name = "FirmaElectronicaPort")
    public FirmaElectronica getFirmaElectronicaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://firma.ws.servicios.bse.com/", "FirmaElectronicaPort"), FirmaElectronica.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FIRMAELECTRONICA_EXCEPTION!= null) {
            throw FIRMAELECTRONICA_EXCEPTION;
        }
        return FIRMAELECTRONICA_WSDL_LOCATION;
    }

}
