
package uy.com.bse.persistence.proxy.objpersonal;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmisionOPersonal", targetNamespace = "http://opersonal.ws.servicios.bse.com/", wsdlLocation = "http://jboss-test.bse.com.uy:8080/bsetiendaws/EmisionOPersonal?wsdl")
public class EmisionOPersonal
    extends Service
{

    private final static URL EMISIONOPERSONAL_WSDL_LOCATION;
    private final static WebServiceException EMISIONOPERSONAL_EXCEPTION;
    private final static QName EMISIONOPERSONAL_QNAME = new QName("http://opersonal.ws.servicios.bse.com/", "EmisionOPersonal");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://jboss-test.bse.com.uy:8080/bsetiendaws/EmisionOPersonal?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMISIONOPERSONAL_WSDL_LOCATION = url;
        EMISIONOPERSONAL_EXCEPTION = e;
    }

    public EmisionOPersonal() {
        super(__getWsdlLocation(), EMISIONOPERSONAL_QNAME);
    }

    public EmisionOPersonal(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMISIONOPERSONAL_QNAME, features);
    }

    public EmisionOPersonal(URL wsdlLocation) {
        super(wsdlLocation, EMISIONOPERSONAL_QNAME);
    }

    public EmisionOPersonal(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMISIONOPERSONAL_QNAME, features);
    }

    public EmisionOPersonal(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmisionOPersonal(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmisionOPersonalTienda
     */
    @WebEndpoint(name = "EmisionOPersonalTiendaPort")
    public EmisionOPersonalTienda getEmisionOPersonalTiendaPort() {
        return super.getPort(new QName("http://opersonal.ws.servicios.bse.com/", "EmisionOPersonalTiendaPort"), EmisionOPersonalTienda.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmisionOPersonalTienda
     */
    @WebEndpoint(name = "EmisionOPersonalTiendaPort")
    public EmisionOPersonalTienda getEmisionOPersonalTiendaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://opersonal.ws.servicios.bse.com/", "EmisionOPersonalTiendaPort"), EmisionOPersonalTienda.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMISIONOPERSONAL_EXCEPTION!= null) {
            throw EMISIONOPERSONAL_EXCEPTION;
        }
        return EMISIONOPERSONAL_WSDL_LOCATION;
    }

}
