
package uy.com.bse.persistence.proxy.objpersonal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmisionOPersonalTienda", targetNamespace = "http://opersonal.ws.servicios.bse.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmisionOPersonalTienda {


    /**
     * 
     * @param usuario
     * @param contrasena
     * @return
     *     returns uy.com.bse.persistence.proxy.objpersonal.PlanesCoberturaTiendaResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaPlanesCobertura", targetNamespace = "http://opersonal.ws.servicios.bse.com/", className = "uy.com.bse.persistence.proxy.objpersonal.ConsultaPlanesCobertura")
    @ResponseWrapper(localName = "consultaPlanesCoberturaResponse", targetNamespace = "http://opersonal.ws.servicios.bse.com/", className = "uy.com.bse.persistence.proxy.objpersonal.ConsultaPlanesCoberturaResponse")
    public PlanesCoberturaTiendaResp consultaPlanesCobertura(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "")
        String contrasena);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @return
     *     returns uy.com.bse.persistence.proxy.objpersonal.TiposMovilidadTiendaResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTiposMovilidad", targetNamespace = "http://opersonal.ws.servicios.bse.com/", className = "uy.com.bse.persistence.proxy.objpersonal.ConsultaTiposMovilidad")
    @ResponseWrapper(localName = "consultaTiposMovilidadResponse", targetNamespace = "http://opersonal.ws.servicios.bse.com/", className = "uy.com.bse.persistence.proxy.objpersonal.ConsultaTiposMovilidadResponse")
    public TiposMovilidadTiendaResp consultaTiposMovilidad(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "")
        String contrasena);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @return
     *     returns uy.com.bse.persistence.proxy.objpersonal.TiposObjetosTiendaResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTiposObjetos", targetNamespace = "http://opersonal.ws.servicios.bse.com/", className = "uy.com.bse.persistence.proxy.objpersonal.ConsultaTiposObjetos")
    @ResponseWrapper(localName = "consultaTiposObjetosResponse", targetNamespace = "http://opersonal.ws.servicios.bse.com/", className = "uy.com.bse.persistence.proxy.objpersonal.ConsultaTiposObjetosResponse")
    public TiposObjetosTiendaResp consultaTiposObjetos(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "")
        String contrasena);

    /**
     * 
     * @param tipoDocumento
     * @param nroCertificado
     * @param documento
     * @param usuario
     * @param contrasena
     * @param nroCotizacion
     * @return
     *     returns uy.com.bse.persistence.proxy.objpersonal.ClienteDeudaTiendaResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "controlarClienteConDeuda", targetNamespace = "http://opersonal.ws.servicios.bse.com/", className = "uy.com.bse.persistence.proxy.objpersonal.ControlarClienteConDeuda")
    @ResponseWrapper(localName = "controlarClienteConDeudaResponse", targetNamespace = "http://opersonal.ws.servicios.bse.com/", className = "uy.com.bse.persistence.proxy.objpersonal.ControlarClienteConDeudaResponse")
    public ClienteDeudaTiendaResp controlarClienteConDeuda(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "")
        String contrasena,
        @WebParam(name = "tipoDocumento", targetNamespace = "")
        String tipoDocumento,
        @WebParam(name = "documento", targetNamespace = "")
        String documento,
        @WebParam(name = "nroCotizacion", targetNamespace = "")
        int nroCotizacion,
        @WebParam(name = "nroCertificado", targetNamespace = "")
        int nroCertificado);

    /**
     * 
     * @param movilidad
     * @param planCobertura
     * @param valorObjeto
     * @param tipoObjeto
     * @param usuario
     * @param contrasena
     * @return
     *     returns uy.com.bse.persistence.proxy.objpersonal.CotizacionOPersonalTiendaResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cotizarOPersonalAnonimo", targetNamespace = "http://opersonal.ws.servicios.bse.com/", className = "uy.com.bse.persistence.proxy.objpersonal.CotizarOPersonalAnonimo")
    @ResponseWrapper(localName = "cotizarOPersonalAnonimoResponse", targetNamespace = "http://opersonal.ws.servicios.bse.com/", className = "uy.com.bse.persistence.proxy.objpersonal.CotizarOPersonalAnonimoResponse")
    public CotizacionOPersonalTiendaResp cotizarOPersonalAnonimo(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "")
        String contrasena,
        @WebParam(name = "planCobertura", targetNamespace = "")
        String planCobertura,
        @WebParam(name = "tipoObjeto", targetNamespace = "")
        String tipoObjeto,
        @WebParam(name = "valorObjeto", targetNamespace = "")
        Double valorObjeto,
        @WebParam(name = "movilidad", targetNamespace = "")
        String movilidad);

    /**
     * 
     * @param tipoDocumento
     * @param marca
     * @param fechaFactura
     * @param serie
     * @param documento
     * @param usuario
     * @param contrasena
     * @param nroCotizacion
     * @param planPago
     * @param modelo
     * @param consumoFinal
     * @return
     *     returns uy.com.bse.persistence.proxy.objpersonal.EmisionOPersonalTiendaResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "emitirOPersonal", targetNamespace = "http://opersonal.ws.servicios.bse.com/", className = "uy.com.bse.persistence.proxy.objpersonal.EmitirOPersonal")
    @ResponseWrapper(localName = "emitirOPersonalResponse", targetNamespace = "http://opersonal.ws.servicios.bse.com/", className = "uy.com.bse.persistence.proxy.objpersonal.EmitirOPersonalResponse")
    public EmisionOPersonalTiendaResp emitirOPersonal(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "")
        String contrasena,
        @WebParam(name = "tipoDocumento", targetNamespace = "")
        String tipoDocumento,
        @WebParam(name = "documento", targetNamespace = "")
        String documento,
        @WebParam(name = "marca", targetNamespace = "")
        String marca,
        @WebParam(name = "serie", targetNamespace = "")
        String serie,
        @WebParam(name = "modelo", targetNamespace = "")
        String modelo,
        @WebParam(name = "nroCotizacion", targetNamespace = "")
        long nroCotizacion,
        @WebParam(name = "planPago", targetNamespace = "")
        String planPago,
        @WebParam(name = "fechaFactura", targetNamespace = "")
        XMLGregorianCalendar fechaFactura,
        @WebParam(name = "consumoFinal", targetNamespace = "")
        String consumoFinal);

}
