
package uy.com.bse.persistence.proxy.pagoelectronico;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PagosElectronicos", targetNamespace = "http://epagos.ws.servicios.bse.com/", wsdlLocation = "http://jboss7-dmz-test.bse.com.uy:8080/bseonlinews7/PagosElectronicos?wsdl")
public class PagosElectronicos_Service
    extends Service
{

    private final static URL PAGOSELECTRONICOS_WSDL_LOCATION;
    private final static WebServiceException PAGOSELECTRONICOS_EXCEPTION;
    private final static QName PAGOSELECTRONICOS_QNAME = new QName("http://epagos.ws.servicios.bse.com/", "PagosElectronicos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://jboss7-dmz-test.bse.com.uy:8080/bseonlinews7/PagosElectronicos?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAGOSELECTRONICOS_WSDL_LOCATION = url;
        PAGOSELECTRONICOS_EXCEPTION = e;
    }

    public PagosElectronicos_Service() {
        super(__getWsdlLocation(), PAGOSELECTRONICOS_QNAME);
    }

    public PagosElectronicos_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAGOSELECTRONICOS_QNAME, features);
    }

    public PagosElectronicos_Service(URL wsdlLocation) {
        super(wsdlLocation, PAGOSELECTRONICOS_QNAME);
    }

    public PagosElectronicos_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAGOSELECTRONICOS_QNAME, features);
    }

    public PagosElectronicos_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagosElectronicos_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PagosElectronicos
     */
    @WebEndpoint(name = "PagosElectronicosPort")
    public PagosElectronicos getPagosElectronicosPort() {
        return super.getPort(new QName("http://epagos.ws.servicios.bse.com/", "PagosElectronicosPort"), PagosElectronicos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagosElectronicos
     */
    @WebEndpoint(name = "PagosElectronicosPort")
    public PagosElectronicos getPagosElectronicosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://epagos.ws.servicios.bse.com/", "PagosElectronicosPort"), PagosElectronicos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAGOSELECTRONICOS_EXCEPTION!= null) {
            throw PAGOSELECTRONICOS_EXCEPTION;
        }
        return PAGOSELECTRONICOS_WSDL_LOCATION;
    }

}
